### ISSUE TITLE
New repository

### ISSUE THREAD

**Issue by notzippy** [revel/rfcs#3]
Not sure where to ask this... so why not here, @brendensoares Can you create a new repository called revel-manifest ? 

The idea behind this is that you can use a tool like https://code.google.com/p/git-repo/ or https://github.com/notzippy/repo-tool to clone multiple repositories at once at a specific version. The manifest file contains a tag or branch, value matching the same as the one the manifest is on.  This allows the repo tool to pull all repositories based on the specific tag

Several different usage scenarios would exist for this.
1. A revel developer who wants to work on a specific branch (remember we were going to try multiple feature branches) - one command would check all these projects into a src folder that you can point your gopath at
2. A web developer wanting to retrieve and stick to a consistent version of revel.
3. A revel documenter, wanting to work on documentation for specific branches

Typical usage commands would be 

`repo init -u git@github.com:notzippy/revel-manifest.git -b master -g all`

Fetch projects labeled with the "all" group on branch master

or

`repo-tool init -u git@github.com:notzippy/revel-manifest.git -b develop -g core,docs`

Fetch projects labeled with the "core" or "docs" group on branch develop

The advantage of this compared to using subprojects or submodules is that you can place the checked out project on a specific path, also you can lean down the checkout by specifying a depth attribute for the clone (makes clone process faster). I started a default manifest for revel here
https://github.com/notzippy/revel-manifest/blob/master/default.xml

**Comment by notzippy** [comment]
Added to meta

**Comment by brendensoares** [comment]
@notzippy these sort of `discuss` topics are normally in the `revel` repo issues.
